export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const CURRENT_USER = "CURRENT_USER";

export const AUTHENTICATION_REQUEST = "AUTHENTICATION_REQUEST";
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE";

export const SOCKET_CONNECTED = "SOCKET_CONNECTED";